boot/urls.py
from django.shortcuts import render
from django.urls import path ##path->8번으로 간다!

from boot import views

app_name = "boot"
urlpatterns = [
    path("base/", views.test),
    path("blog/", views.blog, name="blog"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("home/", views.index, name="home"),
    path("inquiry/create/", views.inquiry_create),
    path("login/", views.login, name="login"),
    path("sign-up/", views.sign_up, name="sign_uo"),
    path("logout/", views.logout, name="logout"),
    
]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include

from boot import views

urlpatterns = [
    path("admin/", admin.site.urls),#####
    path("landing/", include("landing.urls")),
    path("boot/", include("boot.urls")),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("allauth.socialaccount.providers.naver.url")),
    # path("accounts/social/login/cancelled/", views.login),
    # path("accounts/", include("allauth.urls")),


  
    ##########
] 

landing/urls.py
from django.urls import path

from landing import views


app_name = "landing"
urlpatterns = [
    
    path("index/", views.index, name="home"),## 리스트에 정리하는 것
    # path("create/", views.post_create, name="create"),
    path("temptest/", views.temp_test),
    path("read-all/", views.post_read_all, name="read-all"),
    path("read/<int:post_id>/", views.post_read, name="read"),
    path("update/<int:post_id>/",views.post_update, name="update"),
    path("delete/<int:post_id>/", views.post_delete, name="delete"),
    path("create/", views.post_create, name="create"),
    path("path-test/<int:i>/<int:j>/", views.temp_test, name="url_test"),
]

landing/models.py
from turtle import update
from django.db import models




class TempUser(models.Model):
    username = models.CharField(max_length=32)##짧은 글귀를 저장하기 위해서
    email = models.CharField(max_length=32)##짧은 글귀를 저장하기 위해서

class Post(models.Model):##
    title = models.CharField(max_length=32)##짧은 글귀를 저장하기 위해서
    content = models.TextField(blank=True, null=True)##길이를 알 수 없는 글귀(장문위주)
    created_at = models.DateTimeField(auto_now_add=True)##시간과 관련된
    updated_at = models.DateTimeField(auto_now=True)
    writer = models.ForeignKey(
        TempUser, on_delete=models.CASCADE,
        blank=True, null=True
    )

    liked_users = models.ManyToManyField(
        TempUser,
        related_name="user_likes"
    )

    # likes = models.IntegerField(default=0) ##숫자와 관련된

landing/views.py
from multiprocessing import context
import pstats
import random
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
# http응답을 위한 추가 기능삽입
from landing.models import Post


def index(request):
    return render(request, "landing/index.html")

def temp_test(request):

    context = {
        "weather": "맑음",
        "temperature": 5,
        "weather_data" : {
            "weather" : "흐림",
            "temperature": 5
        },
    
        "football_players": [
            {
                "name":"손흥민",
                "team":"토트넘"
            },
            {
                "name":"리오넬 메시",
                "team":"파리셍제르망"
            },
            {
                "name":"이강인",
                "team":"마요르카"
            }
        ]       
    }
                
    return render(request, "landing/temptest.html",context)## 컨텍스트를 리턴해주는거 까먹지 말자

def post_create(request):
    if request.method == "GET":
        # 꼭 대문자로 써야함
        return render(request, "landing/create.html")##urls.py에 연결하기 위함
    elif request.method == "POST":
        # 꼭 대문자로 써야함
        new_post = Post()
        new_post.title = request.POST["title"]
        new_post.content = request.POST["content"]
        new_post.save()
        # print(request.POST["title"])    
        # print(request.POST["content"])
        return HttpResponseRedirect("/landing/create/")
        # http응답을 요청하는 것//요청->응답(HTML을 달라(get) ->포스트 요청-> 계속적으로 로테이션이 돌아감))



def post_read_all(request):
    post_list = Post.objects.all()
    for post in post_list:
        print(post.content)
    context = {
        "posts": post_list##전부다 하는거
    }
    return render(request, "landing/read-all.html", context)


def post_read(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        "post":post##하나만
       
    }

    # print(post_id)
    return render(request, "landing/read.html", context)



        # render(request, "landing/create.html")

def post_update(request, post_id):
    if request.method == "GET":
        post = Post.objects.get(id=post_id)
        context = {
            "post":post
        }
        # 꼭 대문자로 써야함
        return render(request, "landing/update.html", context)
    elif request.method == "POST":
        # 꼭 대문자로 써야함
        target_post = Post.objects.get(id=post_id)
        target_post.title = request.POST["title"]
        target_post.content = request.POST["content"]
        target_post.save()


        # print(request.POST["title"])    
        # print(request.POST["content"])
        return redirect("landing:read", post_id)
        # http응답을 요청하는 것//요청->응답(HTML을 달라(get) ->포스트 요청-> 계속적으로 로테이션이 돌아감))


def post_delete(request, post_id):
    if request.method == "GET":
        post = Post.objects.get(id=post_id)
        context = {
            "post":post
        }
        return render(request, "landing/delete.html", context)
    elif request.method == "POST":
        target_post = Post.objects.get(id=post_id)
        target_post.delete()

def index(request):
    return render(request, "index.html")

def post_create(request):
        if request.method == "GET":
            return render(request, "landing/create.html")
        elif request.method == "POST":
        # print(request.POST["title"])
        # print(request.POST["content"])
            if request.FILES["image"]:
                print(request.FILES["image"])

            new_post = Post()
            new_post.title = request.POST["title"]
            new_post.content = request.POST["content"]
            if request.FILES["image"]:
                new_post.head_image = request.FILES["image"]

        new_post.save()

        # print(request.POST["title"])
        # print(request.POST["content"])
        # return HttpResponseRedirect(reverse("landing:read_all"))

        return redirect("landing:read_all")












# def create_post_page(request):
#     dummy_post_data = [
#         {
#             "title": "Title 1",
#             "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante mauris, eleifend id felis vitae, feugiat volutpat ex. Curabitur vehicula, leo ac aliquet aliquet, nibh lectus accumsan tortor, non bibendum mi arcu quis orci. Proin pellentesque sodales lectus, quis pulvinar odio commodo elementum. Sed erat nulla, accumsan a interdum eu, vehicula sed quam. Suspendisse in posuere libero. Proin ut nunc ac ante fermentum pretium ut non erat. Cras rutrum iaculis aliquet. Cras tincidunt feugiat nibh ut imperdiet.",
#         },
#         {
#             "title": "Title 2",
#             "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante mauris, eleifend id felis vitae, feugiat volutpat ex. Curabitur vehicula, leo ac aliquet aliquet, nibh lectus accumsan tortor, non bibendum mi arcu quis orci. Proin pellentesque sodales lectus, quis pulvinar odio commodo elementum. Sed erat nulla, accumsan a interdum eu, vehicula sed quam. Suspendisse in posuere libero. Proin ut nunc ac ante fermentum pretium ut non erat. Cras rutrum iaculis aliquet. Cras tincidunt feugiat nibh ut imperdiet.",
#         },
#         {
#             "title": "Title 3",
#             "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante mauris, eleifend id felis vitae, feugiat volutpat ex. Curabitur vehicula, leo ac aliquet aliquet, nibh lectus accumsan tortor, non bibendum mi arcu quis orci. Proin pellentesque sodales lectus, quis pulvinar odio commodo elementum. Sed erat nulla, accumsan a interdum eu, vehicula sed quam. Suspendisse in posuere libero. Proin ut nunc ac ante fermentum pretium ut non erat. Cras rutrum iaculis aliquet. Cras tincidunt feugiat nibh ut imperdiet.",
#         },
#         {
#             "title": "Title 4",
#             "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ante mauris, eleifend id felis vitae, feugiat volutpat ex. Curabitur vehicula, leo ac aliquet aliquet, nibh lectus accumsan tortor, non bibendum mi arcu quis orci. Proin pellentesque sodales lectus, quis pulvinar odio commodo elementum. Sed erat nulla, accumsan a interdum eu, vehicula sed quam. Suspendisse in posuere libero. Proin ut nunc ac ante fermentum pretium ut non erat. Cras rutrum iaculis aliquet. Cras tincidunt feugiat nibh ut imperdiet.",
#         }
#     ]


#     new_post = Post()
#     random.shuffle(dummy_post_data)
#     post_data = dummy_post_data[0]
#     new_post.title = post_data["title"]
#     new_post.content = post_data["content"]
#     new_post.save()

#     return render(request, "landing/create.html")

landing/templates/landing/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <form 
  action="{% url 'landing:create' %}" 
  id="post-write" 
  method="post"
  enctype="multipart/form-data"
>
{% csrf_token %}
title: <input type="text" name="title" value="title">
<div>
  <input type="file" name="image">
</div>
<input type="submit" value="submit">

</form>
<textarea name="content" form="post-write" value="submit">Enter Text Here...</textarea>
  
</body>
</html>

landing/templates/landing/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  
  <p>Delete: {{ post.title }}??</p>
  <form action="{% url 'landing:delete' post.id %}"> 게시글 작성 </a>" method="post">
    {% csrf_token %}
    <input type="submit" value="YES">
  </form>
  <a href="/landing/read/{{ post.id }}/">Go Back</a>
  <!-- <form action="/landing/read/{{ post.id}}/" method="get">
    <input type="submit" value="NO">
  </form> -->
   





</body>
</html>

landing/templates/landing/lorem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Position Quiz 4</title>
    <style>
        body {
            margin: 0px;
        }

        #logo {
            font-size: 16pt;
        }

        #top-bar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: sticky;
            top: 0px;
            background-color: aliceblue;
            border-bottom: 0.5px solid black;
            padding-left: 30px;
            padding-right: 30px;
            box-sizing: border-box;
        }

        #user-actions {
            display: flex;
            width: 250px;
            justify-content: space-between;
        }

        #random-content-body {
            width: 75vw;
            margin: auto;
        }

        #chat-button {
            position: fixed;
            /* bottom: 25px; */
            right: 25px;
            font-size: 40px;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 80px;
            height: 80px;
            border-radius: 50%;
            background-color: dodgerblue;
            border: 10px solid cadetblue;
        }
    </style>
</head>
<body>
    <div id="top-bar">
        <p id="logo">Lorem Ipsum</p>
        <div id="user-actions">
            <p><a href="index.html">뒤로가기</a></p>
            <p>로그인</p>
            <p>회원가입</p>
        </div>
    </div>
    <div id="random-content-body">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id malesuada mi, sed interdum dui. Ut ut eros aliquet magna scelerisque consequat. Donec scelerisque eget leo at dignissim. Phasellus tristique lectus ante, ac mollis odio iaculis vitae. Vivamus blandit, enim vel varius consequat, nulla dui facilisis ante, eget bibendum sem augue at odio. Ut viverra efficitur congue. Nulla facilisi. Nullam vulputate urna sit amet lacus consequat, ac convallis sapien pellentesque. Donec efficitur lacinia egestas.
            </p>
            <p>
            Vivamus non est nec augue rutrum blandit et ut nibh. Fusce rutrum auctor dui non sagittis. Aliquam in mollis tortor. Ut nec sagittis justo. Etiam sed mollis metus. Vivamus congue diam quis magna dignissim, vitae ullamcorper libero ultricies. Aenean diam magna, dignissim a ligula at, semper luctus nibh. Nunc auctor neque ac dui porttitor fringilla. Curabitur quis faucibus nisl, vitae faucibus eros.
            </p>
            <p>
            Proin quis accumsan magna, efficitur aliquet leo. Suspendisse lectus turpis, mattis sed consequat nec, faucibus egestas nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla aliquam est aliquam justo pulvinar fermentum. Nam eu scelerisque tortor. Duis rhoncus erat sit amet ligula euismod tincidunt. Sed tortor ante, fermentum non sem ut, euismod eleifend tellus. Ut ullamcorper erat justo, et suscipit dolor sollicitudin vitae. Morbi luctus augue sit amet odio aliquam vestibulum. Donec vulputate, enim et auctor ornare, metus justo tempus justo, id tincidunt lectus nisi eu arcu. Aliquam enim risus, luctus vel sapien eget, cursus blandit tellus. Sed dolor nibh, lacinia vitae sem sed, cursus condimentum tellus. Phasellus a nunc quis lectus facilisis sollicitudin eu quis massa.
            </p>
            <p>
            Nullam sit amet lorem in nisl feugiat faucibus laoreet eget sapien. Fusce vel urna nibh. Pellentesque ut pharetra quam. Proin vestibulum blandit auctor. Nullam luctus varius felis vitae scelerisque. Nunc consequat maximus augue, volutpat feugiat libero rutrum id. Nam vitae lectus nec dui ultricies placerat. Suspendisse ligula eros, auctor a faucibus eget, tempor volutpat sem. Phasellus scelerisque augue ut dui ultrices rutrum. Mauris erat leo, blandit vitae congue euismod, aliquam vitae odio.
            </p>
            <p>
            Aenean gravida enim in enim volutpat egestas. Aenean in pulvinar nisi. Ut imperdiet ac odio ac porttitor. Fusce placerat neque eget neque accumsan rhoncus. Cras vel neque eu libero eleifend rutrum. Donec iaculis magna ac leo tincidunt lacinia. Etiam dapibus, enim tincidunt placerat auctor, ex velit euismod sapien, sit amet sagittis metus nulla aliquet metus. Vivamus vehicula, libero in dapibus elementum, sapien velit semper ante, ut interdum risus orci sed metus. Cras rhoncus dolor a nibh interdum sodales. Praesent iaculis tincidunt leo, et blandit lectus placerat et. Mauris at lacus ipsum.
            </p>
            <p>
            Integer at eros tellus. Duis vel ante quam. Quisque ut nibh et felis gravida mattis. Nulla fermentum nunc luctus lacinia fringilla. Fusce ac vestibulum ex, quis tincidunt massa. Aenean scelerisque ultricies neque vel placerat. Sed egestas ultricies risus, et mollis metus vehicula eget. Aliquam elementum ligula in tellus ultricies viverra. Integer ligula elit, blandit id lacinia quis, sagittis quis leo. Sed euismod erat ipsum, in placerat augue rutrum eget. Donec tortor ipsum, semper id sollicitudin a, accumsan in lorem.
            </p>
            <p>
            Integer ultricies ex eget est luctus, elementum consequat mauris suscipit. Sed non risus id augue tincidunt interdum. Donec nec orci hendrerit, gravida est eget, semper nunc. Cras pulvinar luctus hendrerit. Maecenas volutpat, eros quis mollis pulvinar, neque orci vestibulum libero, sit amet semper odio ligula at neque. Etiam vulputate est ac purus feugiat efficitur. Integer scelerisque nisi nulla, at placerat lorem venenatis in.
            </p>
            <p>
            Vivamus ut scelerisque quam. Duis ut bibendum felis, ut pulvinar orci. Curabitur eget neque in nibh ultrices fermentum eu vel risus. Quisque in turpis ligula. Etiam id viverra lectus. Cras vulputate vel elit eu volutpat. Etiam vitae elit sagittis, eleifend diam et, blandit mi. Donec eleifend sem ligula, non mollis neque finibus sit amet. Mauris quis efficitur turpis. Curabitur non bibendum odio. Integer suscipit rhoncus dui, sed venenatis felis fringilla sit amet. Nam egestas est libero. Nullam convallis sollicitudin sapien. Sed imperdiet faucibus metus a molestie. Duis diam dui, ullamcorper at nunc at, lacinia tempus neque. Ut sit amet justo ut neque aliquet pellentesque vel sed lectus.
            </p>
            <p>
            Vestibulum dapibus quam a massa finibus maximus. Vestibulum enim purus, fermentum ornare enim eu, dictum commodo neque. Aliquam semper tincidunt porta. Vivamus fringilla id sem ac laoreet. Vestibulum vel felis mattis, vulputate tellus et, dignissim nulla. Aliquam ultrices ultrices ex at pellentesque. Integer pellentesque ipsum interdum iaculis pulvinar. Mauris quis lacus ultrices, sodales risus ultricies, dapibus tortor. Proin gravida mattis odio placerat congue. Vivamus pulvinar rhoncus nunc, id commodo odio placerat elementum.
            </p>
            <p>
            Suspendisse quis pharetra quam. Proin vulputate lacus erat, vitae facilisis justo mattis ac. Vivamus tempus aliquam ornare. Sed porta egestas massa, eget aliquam nunc gravida at. Duis porttitor lectus vel tellus tempor, eget dictum orci fermentum. Ut sed augue eget tellus auctor sollicitudin. Donec ut efficitur lacus.
            </p>
    </div>
    <div id="chat-button">채팅</div>
</body>
</html>

landing/templates/landing/pokeball.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Position Quiz 2</title>
    <style>
        .container {
            position: relative;
            width: 500px;
            height: 500px;
            border: 1px solid white;
        }

        .ball-top {
            width: 450px;
            height: 225px;
            border-top-left-radius: 225px;
            border-top-right-radius: 225px;
            background-color: red;
            border: 0.5px solid grey;
            box-sizing: border-box;
        }

        .ball-bot {
            width: 450px;
            height: 225px;
            border-bottom-left-radius: 225px;
            border-bottom-right-radius: 225px;
            border: 0.5px solid grey;
            box-sizing: border-box;
        }

        .ball-belt {
            position: absolute;
            top: 225px;
            width: 460px;
            height: 50px;
            background-color: white;
            border: 1px solid grey;
        }

        .ball-button-out {
            position: absolute;
            top: 200px;
            width: 100px;
            height: 100px;
            border-radius: 50%;
            border: 1px solid black;
            background-color: white;
        }

        .ball-button-in {
            top: 200px;
            width: 80px;
            height: 80px;
            border-radius: 50%;
            border: 1px solid black;
            background-color: white;
        }

        .flex-center {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .flex-column {
            display: flex;
            flex-direction: column;
        }
    </style>
</head>
<body>
    <div class="container flex-center flex-column">
        <div class="ball-top"></div>
        <div class="ball-bot"></div>
        <div class="ball-belt"></div>
        <div class="ball-button-out flex-center">
            <div class="ball-button-in"></div>
        </div>
    </div>
    <a href="landing/index">뒤로가기</a>
</body>
</html>

landing/templates/landing/read self.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post Read</title>
</head>
<body>
  <h1>Post self</h1>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad, velit eligendi voluptatem totam consequuntur illo facere esse, dolorum non perferendis vel excepturi. Iure quam optio asperiores minus quidem atque saepe!</p>

</body>
</html>

landing/templates/landing/read-all.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post Read All</title>
</head>
<body>
  {%if posts %}
     <ul>
       {% for post in posts %}
       <li><a href="{% url 'landing:read' post.id %}">{{ post.title }}</a></li>

        {% endfor %}
     </ul>
  {% else %}
  <!-- 이건 HTML 주석입니다 -->
  {#이건 Django Template 주석입니다.#}
  <p>아직 작성된 글이 없습니다.</p>
  {% endif %}
  

  <a href="{% url 'landing:create' %}"> create </a>


</body>
</html>

landing/templates/landing/read.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post Read</title>
</head>
<body>

   
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
  <div>
    <a href= "{% url 'landing:update' post.id %}"> 게시글 작성 </a>>Edit</a>
  </div>
  <div>
    <a href="{% url 'landing:delete' post.id %}">Delete</a>
  </div>
 

</body>
</html>

landing/templates/landing/temptest.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
     <!-- <p>오늘 날씨는 {{ weather }}이며, 온도는 섭씨{{ temperature }}도 입니다. </p>
     <p>오늘 날씨는 {{weather_data.weather}}이며, 온도는 섭씨{{weather_data.temperature}}도 입니다. </p>
     <p>는 {{weather}}이며, 온도는 섭씨{{temperature}}도 입니다. </p>
     <p>{{football_players.0.name}}는 {{football_players.0.team}}입니다. </p>
     <p>{{football_players.1.name}}는 {{football_players.1.team}}입니다. </p>
     <p>{{football_players.2.name}}는 {{football_players.2.team}}입니다. </p>


     {% for post in football_players %}
     <p>{{post.name}}는 {{post.team}}입니다. </p>
       {% endfor %}

    {% for plyaer in baseball_plyers %}
    <p>{{post.name}}는 {{post.team}}입니다. </p>
    {% empty %}
    <p>야구선수는 없습니다.</p>
    {% endfor %} -->
    {% comment %}
    <p>
      오늘의 기온은
      {% if not weather.temperature %}
      알 수 없습니다.
      {% elif weather.temperature < 10 %}
      {{ weather.temperature }} 도 이며, 매우 춥습니다.
      {% elif weather.temperature > 30 %}
      {{ weather.temperature }} 도 이며, 매우 덮습니다.
      {% else %}
      {{ weather.temperature }} 도 이며, 애매합니다.
      {% endif %}
    </p>
    
    
    <h1> {% url 'url_test' 1 2 %}</h1>
    
    <h1> {% url 'home' %}</h1>

    {% lorem 2 w %}
    {% lorem 3 p random %}
    It is {% now "jS F Y H:i" %}<br>
    
    {% now "Y m d" %}
    {# 2022-04-21#}<br>
    {% endcomment %}


    <h1> {% url 'landing:home' %}</h1>
    
    I know {{ football_players|length }} football_players!
    </body>    


   
</html>

landing/templates/landing/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post Create</title>
</head>
<body>
  <form action="{% url 'landing:update' post.id %}" id="post-edit" method="post">
        
    {% csrf_token %}
    <!-- 장고 보안설정 상 필요한 기능 -->
     Title: <input type="text" name="title" value="{{post.title}}">
     <!-- view.py에 있는 포스트에 기록되는 것이 name이다 -->
     <!-- Title은 HTML에서 보여주는거고 인풋 타입을 텍스트, 네임 타이틀? 벨류는 안쪽에 실제 이름 준다 -->
     <input type="submit" value="submit">
    
  </form>
  <textarea name="content" form="post-edit"> {{ post.content }}</textarea>
  
    <!-- form에 있는 ID로 귀속시킨다 -->
</body>
</html>